### ISSUE TITLE
TypeError: Buffer.isBuffer is not a function

### ISSUE THREAD

**Issue by ArtieReus** [PeculiarVentures/pvtsutils#8]
Hi. thanks also for the great set of libraries :)

I ran into an issue when using @peculiar/x509:
```
error:  TypeError: Buffer.isBuffer is not a function
    at Function.toView (index.js:26:54)
    at Function.toUint8Array (index.js:23:1)
    at Function.ToBinary (index.js:237:1)
    at Function.toArrayBuffer (x509.es.js:248:31)
    at new PemData (x509.es.js:266:1)
    at new PublicKey (x509.es.js:291:1)
    at Function.create (x509.es.js:827:1)
```

I am getting this error when using the function 

`x509.SubjectKeyIdentifierExtension.create(keys.publicKey)`

also using following function:

`x509.PemConverter.encode( pkcs8, "private key")`

both uses the x509.PemConverter class which uses pvtsutils under the hood...

When debbuging the error I can see the the Buffer object looks following:
`{INSPECT_MAX_BYTES: 50, kMaxLength: 2147483647, Buffer: ƒ, SlowBuffer: ƒ}`
and the attribute Buffer.Buffer has the the method `isBuffer()`

`Buffer.Buffer.isBuffer()`
https://github.com/PeculiarVentures/pvtsutils/blob/b0d4465dd828215b88320e72f81ee61a3dfe3e71/src/buffer_source_converter.ts#L36

I am running the x509 library version 1.6.1 from yarn which has a dependency to pvtsutils 1.2.1 which are both the latest. Can someone help me here?

**Comment by microshine** [comment]
Are you running these modules in NodeJS?

`Buffer.Buffer` looks too strange

In my case `Buffer` in nodejs is
```
% node
Welcome to Node.js v16.13.0.
Type ".help" for more information.
> Buffer
[Function: Buffer] {
  poolSize: 8192,
  from: [Function: from],
  of: [Function: of],
  alloc: [Function: alloc],
  allocUnsafe: [Function: allocUnsafe],
  allocUnsafeSlow: [Function: allocUnsafeSlow],
  isBuffer: [Function: isBuffer],
  compare: [Function: compare],
  isEncoding: [Function: isEncoding],
  concat: [Function: concat],
  byteLength: [Function: byteLength],
  [Symbol(kIsEncodingSymbol)]: [Function: isEncoding]
}
```

**Comment by microshine** [comment]
I can reproduce the same behavior if using `require("buffer")` module
```
> var Buffer = require("buffer")
undefined
> Buffer
{
  Blob: [class Blob],
  resolveObjectURL: [Function: resolveObjectURL],
  Buffer: [Function: Buffer] {
    poolSize: 8192,
    from: [Function: from],
    of: [Function: of],
    alloc: [Function: alloc],
    allocUnsafe: [Function: allocUnsafe],
    allocUnsafeSlow: [Function: allocUnsafeSlow],
    isBuffer: [Function: isBuffer],
    compare: [Function: compare],
    isEncoding: [Function: isEncoding],
    concat: [Function: concat],
    byteLength: [Function: byteLength],
    [Symbol(kIsEncodingSymbol)]: [Function: isEncoding]
  },
  SlowBuffer: [Function: SlowBuffer],
  transcode: [Function: transcode],
  kMaxLength: 4294967296,
  kStringMaxLength: 536870888,
  btoa: [Function: btoa],
  atob: [Function: atob],
  constants: { MAX_LENGTH: 4294967296, MAX_STRING_LENGTH: 536870888 },
  INSPECT_MAX_BYTES: [Getter/Setter]
}
```

**Comment by ArtieReus** [comment]
Thank you for the fast response :)
No. I am running the the library x509 im browser from a react app. The libraries as I said are from yarn.

**Comment by ArtieReus** [comment]
checking the dev dependecies in the react app I can see following dependency:
`"buffer": "^6.0.3"`
which would be this lib
`https://yarnpkg.com/package/buffer`

**Comment by microshine** [comment]
I've published the new version. Please try `pvtsutils@1.2.2`

**Comment by ArtieReus** [comment]
Would you please also update the dependencies of x509 so I can test it:
https://github.com/PeculiarVentures/x509/blob/master/package.json
this library still use the older version 1.2.1.

**Comment by ArtieReus** [comment]
I found the root cause. We use webpack 5 (this version differs from the old versions which included modules by default) and the Buffer module isn't included by default. To avoid compile errors we added the node Buffer module like this:

```
      new webpack.ProvidePlugin({
        process: require.resolve("process/browser"),
        Buffer: require.resolve("buffer/"),
      }),
```

Require returns the whole module, not the default. We fixed this changing how we load the Buffer module:

```
      new webpack.ProvidePlugin({
        process: require.resolve("process/browser"),
        // https://github.com/PeculiarVentures/pvtsutils/issues/8
        Buffer: [require.resolve("buffer/"), "default"],
      }),
```

This is probably not the best fix because there are other libraries that call intern the default property. 

Your fix wouldn't help if the Buffer module isn't with default loaded do to if case is never true. You just avoid the exception.

**Comment by ArtieReus** [comment]
we found the right way to include Buffer module in webpack 5:

```
const webpackConfig = {
    resolve: {
        fallback: {
            buffer: require.resolve('buffer/'),
        },
    },
    plugins: [
        new webpack.ProvidePlugin({
            Buffer: ['buffer', 'Buffer'],
        }),
    ],
};
```

sorry for the trouble and thx again for your time. Webpack 5 behaviours bit different.
